name: Build report
on:
  push:
    branches:
    - master
  schedule:
  - cron: '0 6 * * *'

jobs:
  build-report:
    name: Build report
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Unit tests
      run: |
        go test ./...
    - name: Build html file
      env:
        GITHUB_TOKEN: ${{ secrets.REPORTS_TOKEN}}
      run: |-
        go run ./cmd > report.html
        if ! [ -s report.html ]; then
          echo ::error::Generated html file is empty
          exit 1
        fi
    - name: Upload report
      # actions/upload-artifact@v1
      uses: actions/upload-artifact@3446296
      with:
        name: report
        path: report.html
